# Generated by Django 3.0.4 on 2020-04-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_auto_20200412_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
