# Generated by Django 3.0.4 on 2020-04-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_profile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='media'),
        ),
    ]
